openapi: 3.0.0
info:
  title: Activity API
  description: Activity logging endpoints
  version: 1.0.0

paths:
  /api/activity:
    get:
      summary: Get activity log
      description: Get chronological history of admin actions
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            example: 50
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            example: 0
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ActivityLogEntry'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unauthorized"

components:
  schemas:
    ActivityLogEntry:
      type: object
      properties:
        id:
          type: integer
          example: 1
        action:
          type: string
          enum: [CREATE, DELETE]
          example: "CREATE"
        entity_type:
          type: string
          enum: [expense, user, group]
          example: "expense"
        entity_id:
          type: integer
          example: 1
        details:
          type: string
          example: "Created expense: Dinner at restaurant"
        created_at:
          type: string
          format: date-time
          example: "2023-01-01T00:00:00Z"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
